#! /bin/bash

device=`df | grep "/datax$" | awk '{print $1}' | sed 's/1//g' | awk -F/ '{print$NF}'`
echo $device
iostat -xk 2 2 | grep $device | tail -1
iostat -xk 2 2 | grep $device | tail -1 | awk '{print $6,$7}'
