#! /bin/bash

#foreach i (0 1 2 3 4 5 6 7)
#  echo blc$i
#  ssh blc$i 'iostat -xk 2 2 | grep "^sd" | tail -1'
#end

for h in blc0{0..7}; 
do ssh $h /home/jkyle/GBT-ADQ/mysql/all_check_iostats_assist; done
