#! /bin/bash

hosts="${@:-$(echo blc0{0..7})}"

for h in $hosts; do 
  ssh $h '/home/jkyle/GBT-ADQ/mysql/plot_last' & 
done

#for x in "$(./ls_last)"; do
#  for h in blc0{0..7}; do 
#    ssh $h 'bl_raw_wf.rb -d /home/jkyle/GBT-ADQ/mysql/PNG/test{0001..0050}.png/png /datax/dibas/AGBT*/*/*/$x
