#! /bin/bash

for h in blc0{0..7}; do ssh $h 'ls /datax/dibas/AGBT17A_999_*/GUPPI/*/ | tail -1 > x{0..7} | bl_raw_wf.rb -d /home/jkyle/GBT-ADQ/mysql/PNG/test.png/png /datax/dibas/AGBT17A_999_*/GUPPI/*/i' ; done
