#! /usr/bin/python

#import Image
#import redis
#import StringIO

#output = StringIO.StringIO()
#im = Image.open("/home/jkyle/GBT-ADQ/mysql/PNG/blc02/blc02_guppi_57936_17064_DIAG_PSR_J1935+1616_0001.0013..png")
#im.save(output, format=im.format)

#r = redis.StrictRedis(host='104.196.249.7')
#r.set('imagedata', output.getvalue())
#output.close()

import Image
import redis
import StringIO
import glob
import subprocess

output = StringIO.StringIO()
node_path = glob.glob("/home/jkyle/GBT-ADQ/mysql/PNG/blc0*/*.png.png")
#print(node_path)

for i in node_path:
    print(i)
    path = (i.strip("/home/jkyle/GBT-ADQ/mysql/PNG/blc/, .raw.png.png"))
    i_path = (path[3:])
    print(i_path)
    im = Image.open(i)
    im.save(output, format=im.format)
    r = redis.StrictRedis(host='104.196.249.7')
    r.set(i_path, output.getvalue())
    o_path = ("\'"+str(i_path)+"\'")
    print(o_path)
    filename = (str(i_path[:11]+".png"))
    print(filename)
    #subprocess.check_call(["redis-cli", "-h", "104.196.249.7", "--raw", "get", str(o_path), ">", str(filename)])
    #print(test)
output.close()
