#! /bin/bash

for h in blc0{0..7}; do ssh $h 'bl_raw_wf.rb -d /home/jkyle/GBT-ADQ/mysql/PNG/070517{0001..0200}.png/png /datax/dibas/AGBT17A_999_68/GUPPI/BLP00/blc00_guppi_57898_18622_DIAG_KIC8462852_0023.00*.raw' ; done
