#! /bin/bash

#echo "select * from status;" | mysql -N -h gbtdata.gbt.nrao.edu -u gbtstatus --password=w3bqu3ry gbt_status
echo "select * from status;" | mysql -h gbtdata.gbt.nrao.edu -u gbtstatus --password=w3bqu3ry -E gbt_status
