#! /usr/bin/env python

import subprocess

Ant = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_ant")
#uses a SQL query to check ant_motion

print("\n<br>")

if Ant.strip("\n") == "Stopped":
	print("Dish is stopped." + "\n<br>")
	stopped = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/ls_last")
	print(stopped)
elif Ant.strip("\n") == "Slewing":
	print("Dish is slewing." + "\n<br>")
	slewing = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/ls_last")
	print(slewing)
#	while slewing:
#		for x in slewing:	
#			subprocess.check_output("bl_raw_wf.rb -d /tmp/test.png/png" + slewing)
	#[2]create a new (bl_raw_wf.rb -d /tmp/hello.png/png some_raw_data_file.raw) bash script
	#enter [1] into [2] to generate a plot to a location (/tmp/filename.png from [2])
		
else:
	print("Dish is " + Ant.lower().strip("\n") + "\n<br>")
	other = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/ls_last")

UTC = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_utc")
print("UTC: " + UTC.strip("\n") + "\n<br>")

DATE = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_date")
print("DATE: " + DATE.strip("\n") + "\n<br>")

DATA = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_data")
print("DIRECTORY: " + DATA.strip("\n") + "\n<br>")

REMAINING = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_remaining")
print("TIME REMAINING: " + REMAINING.strip("\n") + "\n<br>")

LENGTH = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_scan_length")
print("SCAN LENGTH: " + LENGTH.strip("\n") + "\n<br>") 
#what units is this in?

SOURCE = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_source")
print("SOURCE: " + SOURCE.strip("\n") + "\n<br>")

RA = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_ra")
RA1 = float(RA.strip("(RA), \n"))
print("RA: " + str(RA1) + "\n<br>")

DEC = subprocess.check_output("/home/jkyle/GBT-ADQ/mysql/show_mysql_dec")
DEC1 = float(DEC.strip("(Dec), \n"))
print("DEC: " + str(DEC1) + "\n<br>")

print("=================================")

